name: Build and Push Docker Image

# Этот сценарий запускается при любом push в ветку 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Входим в реестр контейнеров GitHub
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Новый шаг: Преобразуем имя репозитория в нижний регистр с помощью команды
      - name: Convert repository name to lowercase
        id: string
        run: echo "repo_lc=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # 4. Шаг сборки и публикации (теперь использует результат шага 3)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.string.outputs.repo_lc }}:latest
